language: nix
sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode8.2
env:
- VERSION=0.3 CARDANO_SL_BRANCH=csla-50-macos NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/09c7601c204016c8ecdefd474f721fb841e834df.tar.gz
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- travis_retry curl -L https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64 | tar
  xz --strip-components=1 -C ~/.local/bin
- travis_retry curl -o daedalus-bridge.tar.xz https://s3.eu-central-1.amazonaws.com/cardano-sl-travis/daedalus-bridge-$TRAVIS_OS_NAME-$CARDANO_SL_BRANCH.tar.xz
- mkdir -p node_modules/daedalus-client-api/
- du -sh daedalus-bridge.tar.xz
- tar xJf daedalus-bridge.tar.xz --strip-components=1 -C node_modules/daedalus-client-api/
- echo "cardano-sl build id is $(cat node_modules/daedalus-client-api/build-id)"
- nix-shell --run "npm install"
script:
- export DAEDALUS_VERSION=$VERSION.$TRAVIS_BUILD_NUMBER
- export SSL_CERT_FILE=$NIX_SSL_CERT_FILE
- mv node_modules/daedalus-client-api/{log-config-prod.yaml,cardano-node,cardano-launcher}
  installers/
- rm node_modules/daedalus-client-api/cardano-*
- nix-shell --run "npm run package -- --icon installers/icons/256x256"
- echo "Size of Electron app is $(du -sh release)"
- pushd installers
- stack --no-terminal --nix build --exec make-installer --jobs 2
- mkdir -p dist
- popd
notifications:
  slack:
    secure: hfzreJ033RxFI2UYtcGJ+MFgQX08UyUnQwhb8X8CuVuIZXDWhxz9JLMEUuL6QqogtffbiqfqIhyDwZ0PsE3aEJaHQAQ7lxJkMjZFU/o+CYvHBQy+WYCa/sFM0C8cEXn3Wb/LmhjvtKAgF302tnD5PAPglZTGtCJHpihKG/Wc+YwF2aFSon0DqoMtVmwVPvhD/WlAHyszARsE9C7jH7jN43gwupAmwj7QLH+kd96HKrrc2ItgMS0f5ucFnpM900c9LwhE5StxVdgTXLnogWQKcd1f4DwTNoXfS3Dy6VJkKj049VScvavcFcVPBL9xU62SMMy/eS/yRcHZkxJehUi16aoir2GXNZOKjQVQ85zEQofQgkR+b4roJJmtWJuCoyE0nptoHgDi4BlLwFuC1g7pkngtLvo3BrG3IjhV+s7QuhxFA9aA8MBQDTRBQNeZdU2I/iwJaYsggGQ2JYA/B2AE4C0sentbegGumsY4fah6HVQGOOZoCl3k9fmMDS42/D55kdteRAQBZBlixLHMXTsMf90jcJJGi/vkzVEnhby63RdTRNDW6MBA6RgvUIpI0VQgAIEM8LFHMNeHMYLoj++NnSI3gCrX8zi8nrnCUJmpCQ89WLDRbVy3rFltgcd7ds8SlRxMtSXCO9lulq/Q6Gk65mRhuq/My0FqBbT+DQUBg04=
deploy:
  provider: s3
  access_key_id: AKIAJKSJR3FUN3CWKC5Q
  secret_access_key:
    secure: KL0IpBTLy54CC6w48E7t19uEME1lcdWLZ1RP0qz7jm9A0J58RnBn4VqQL86vXZZZF3L6s4BM5bsD+mOXQ88ePzL4UNL0swJijFI4jh1cv5RsOpoFJc5ULxQWm/ybGqKt2I9kF0TRwI23ilKkxz531cRBmoIbKSDEbDr8Tn7n1gU9ubhAJTI0/Gy1jnrVwQejoZMTEpJJcti1o046wJd0GEJpA88dXPjvi3WXMBcQ1acRxd5tkEjLooScD7CijdUgHTGZC/HvRLY+6SdI8pHaB8/yhli87MBODqpdMstV9zPZI2bJiUDPNaFL+goGA1+4CQnmfyBNfHijDnuBMNTUcj00WHCMJcuLcXM42fli6gO2iivNEe8pz+3Jvz3142hJL8seHm9//QDsGZg7HUYYiPGbDSmug8knh9Zsk8QZUtxlXBNvQqZe2Q289cGzW9Hoo+tNgCvpaUWkBNe/XUXTI2HoE5XkrziRwyVLaXj5Yz7ncjMkwIljrLCxuDS3dT53lwxK7NkLmWovp8r0gL/8szoqTMdKLPNQXOa9dknlW9L905PKOjON1F5SCHc0JKREnQQFNrbx4X1bjVa++Fv6Ix42XBvn7h2MT3NorjSlvyKwBTUeQf5bYD6603Q9YCqsZgEnG0uB3yWvgFXQ0PKH/5htjBwWWQJ4PxLe+mhZ9Jw=
  bucket: daedalus-travis
  region: eu-central-1
  local_dir: installers/dist
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true
