version: 1.0.{build}

environment:
  nodejs_version: "6"
  NETWORK: "mainnet"
  AWS_ACCESS_KEY_ID:
    secure: OJTyvhi9DM4WzXkurTryP6CxiHcklNxjuHdVxc+D85E=
  AWS_SECRET_ACCESS_KEY:
    secure: hlqRod4ZR7cIPZWfLZbn2feAKbTWSAj5oNTqa7zXpSqQmNPCiAzieyVZ80/Mx5cU
  CERT_PASS:
    secure: 9tjYxdz1fqibx1WOrP5yn32iwbEXeYx+Btb5QJqHvMO4Ng2/yUtPi00/ZMXihFWV
  # Avoid long paths on Windows
  STACK_ROOT: "c:\\sr"

build: off

cache:
  - C:\sr -> installers/cardano-installer.cabal
  - C:\sr -> installers/stack.yaml

install:
  - ps: Install-Product node $env:nodejs_version x64
  - IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER aws s3 cp --region eu-central-1 s3://iohk-private-2/iohk-windows-certificate-2.p12 C:/iohk-windows-certificate.p12

test_script:
  - scripts\build-installer-win64.bat %APPVEYOR_BUILD_VERSION% master

artifacts:
  - path: release\win32-x64\Daedalus-win32-x64
    name: Daedalus Electron application
    type: zip
  - path: installers\daedalus-win64-*-installer.exe
    name: Daedalus Win64 Installer
  - path: node_modules\daedalus-client-api\build-id
    name: cardano-sl-build-id
